name: Build FFmpeg RPMs

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - el7
          - el8
          - el9
    name: build (${{ matrix.osversion }})
    runs-on: ubuntu-20.04
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:${{ matrix.osversion }}-oc10.3
    steps:
      - uses: actions/checkout@v2

      - name: download static-ffmpeg
        working-directory: rpmbuild/SPECS
        run: |
          spectool -g -R ffmpeg-static.spec

      - name: build ffmpeg rpm
        working-directory: rpmbuild/SPECS
        run: |
          rpmbuild -ba ffmpeg-static.spec

      - name: list rpms
        working-directory: rpmbuild/RPMS/noarch
        run: |
          du -hs ./*.rpm

      - name: configure s3cmd
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          echo "host_base = ${S3_HOST}" > "$HOME/.s3cfg"
          echo "host_bucket = ${S3_HOST}" >> "$HOME/.s3cfg"
          echo "bucket_location = us-east-1" >> "$HOME/.s3cfg"
          echo "use_https = True" >> "$HOME/.s3cfg"
          echo "access_key = ${S3_ACCESS_KEY}" >> "$HOME/.s3cfg"
          echo "secret_key = ${S3_SECRET_KEY}" >> "$HOME/.s3cfg"
          echo "signature_v2 = False" >> "$HOME/.s3cfg"

      - name: publish repository rpm
        working-directory: rpmbuild/RPMS/noarch
        run: |
          s3cmd put -P ffmpeg*.rpm "s3://opencast-rpmbuild/rpms/${{ matrix.osversion }}/ffmpeg/"
          rm ffmpeg*.rpm

      - name: publish srpms
        working-directory: rpmbuild/SRPMS
        run: |
          s3cmd put -P ffmpeg*.src.rpm "s3://opencast-rpmbuild/srpms/${{ matrix.osversion }}/ffmpeg/"

      - name: send notification
        working-directory: rpmbuild/SRPMS
        env:
          MATRIX_PASS: ${{ secrets.MATRIX_PASS }}
          MATRIX_USER: ${{ secrets.MATRIX_USER }}
          URL_LOGIN: 'https://matrix.org/_matrix/client/r0/login'
          URL_LOGOUT: 'https://matrix.org/_matrix/client/r0/logout'
          URL_MESSAGE: 'https://matrix.org/_matrix/client/r0/rooms/%21gwaqKjZRpCQkpkTVwh%3Amatrix.org/send/m.room.message'
        run: |
          MESSAGE="Finished building FFmpeg $(sed -n 's_%define  date *__p' ffmpeg-static.spec) RPMs (${{ matrix.osversion }})"
          TOKEN="$(curl -s -XPOST -d '{"type":"m.login.password", "user":"'"$MATRIX_USER"'", "password":"'"$MATRIX_PASS"'", "initial_device_display_name":"GitHub Actions"}' "$URL_LOGIN" | jq -r .access_token)"
          curl -s -XPOST -d '{"msgtype":"m.text", "body":"'"${MESSAGE}"'"}' "${URL_MESSAGE}?access_token=${TOKEN}"
          curl -s -XPOST "${URL_LOGOUT}?access_token=${TOKEN}"
