name: Build RPMs

on:
  push:
    branches:
      - 'r/*'

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - el7
          - el8
    name: build (${{ matrix.osversion }})
    runs-on: ubuntu-20.04
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:${{ matrix.osversion }}
    steps:
      - uses: actions/checkout@v2

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: clone mvn.opencast.org
        run: |
          git clone --depth 1 https://github.com/opencast/mvn.opencast.org.git

      - name: clone opencast
        run: |
          git clone https://github.com/opencast/opencast.git

      - name: prepare additional maven repository
        working-directory: opencast
        run: |
          sed -i "s_https://mvn.opencast.org/_file://$(readlink -f ../mvn.opencast.org)_" pom.xml

      - name: show build ref
        id: build_ref
        run: |
          sed -n 's/%define srcversion \(.*\)$/\1/p' rpmbuild/SPECS/opencast.spec \
            | tee ~/version

      - name: checkout opencast ref
        working-directory: opencast
        run: |
          git checkout $(cat ~/version)

      - name: build opencast
        working-directory: opencast
        run: >
          mvn
          --batch-mode
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dcheckstyle.skip=true
          -DskipTests
          clean install

      - name: list distributions to build
        run: |
          find opencast/build/ -type f -name 'opencast-dist-*gz' \
            | sed 's/^.*opencast-dist-\([^-]*\)-.*$/\1/' \
            | tee rpmbuild/SPECS/dists

      - name: move build artifacts
        run: |
          cp -rv rpmbuild/ ~
          mv -v opencast/build/opencast-dist-*.tar.gz ~/rpmbuild/SOURCES/

      - name: build rpms
        working-directory: /github/home/rpmbuild/SPECS
        run: |
          for dist in $(cat dists); do
            rpmbuild -ba -D "ocdist ${dist}" opencast.spec
          done

      - name: list rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          du -hs opencast*.rpm

      - name: configure s3cmd
        env:
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: |
          cp s3cfg ~/.s3cfg
          sed -i "s/S3_KEY/${S3_KEY}/" ~/.s3cfg
          sed -i "s/S3_SECRET/${S3_SECRET}/" ~/.s3cfg

      - name: publish rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          s3cmd put --no-check-md5 *.rpm "s3://public/rpms/${{ matrix.osversion }}/$(cat ~/version)/"

      - name: publish srpms
        working-directory: /github/home/rpmbuild/SRPMS
        run: |
          s3cmd put --no-check-md5 opencast*-allinone-*.src.rpm "s3://public/srpms/${{ matrix.osversion }}/$(cat ~/version)/"
