name: Build RPMs

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:el8
    steps:
      - uses: actions/checkout@v2

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: where am i
        run: |
          pwd
          cd ~
          pwd

      - name: clone opencast
        run: |
          git clone https://github.com/opencast/opencast.git

      - name: show build tag
        run: |
          sed -n 's/%define srcversion \(.*\)$/\1/p' rpmbuild/SPECS/opencast.spec

      - name: checkout tag
        working-directory: opencast
        run: |
          git checkout $(sed -n 's/%define srcversion \(.*\)$/\1/p' ../rpmbuild/SPECS/opencast.spec)

      - name: build opencast
        working-directory: opencast
        run: >
          mvn
          --batch-mode
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dcheckstyle.skip=true
          -DskipTests
          clean install

      - name: list distributions to build
        run: |
          find opencast/build/ -type f -name 'opencast-dist-*gz' \
            | sed 's/^.*opencast-dist-\([^-]*\)-.*$/\1/' \
            | tee rpmbuild/SPECS/dists

      - name: moce build artifacts
        run: |
          mv -v opencast/build/opencast-dist-*.tar.gz rpmbuild/SOURCES/

      - name: build rpms
        working-directory: rpmbuild/SPECS
        run: |
          for dist in $(cat dists); do
            rpmbuild -ba -D "ocdist ${dist}" opencast.spec
          done

      - name: build rpms
        working-directory: rpmbuild/RPMS/noarch
        run: |
          ls -lh
