name: Build RPMs

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:el8
    steps:
      - uses: actions/checkout@v2

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: where am i
        run: |
          pwd
          cd ~
          pwd

      - name: clone opencast
        run: |
          git clone https://github.com/opencast/opencast.git

      - name: show build ref
        id: build_ref
        run: |
          sed -n 's/%define srcversion \(.*\)$/\1/p' rpmbuild/SPECS/opencast.spec

      - name: checkout opencast ref
        working-directory: opencast
        run: |
          git checkout $(sed -n 's/%define srcversion \(.*\)$/\1/p' ../rpmbuild/SPECS/opencast.spec)

      - name: build opencast
        working-directory: opencast
        run: >
          mvn
          --batch-mode
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dcheckstyle.skip=true
          -DskipTests
          clean install

      - name: list distributions to build
        run: |
          find opencast/build/ -type f -name 'opencast-dist-*gz' \
            | sed 's/^.*opencast-dist-\([^-]*\)-.*$/\1/' \
            | tee rpmbuild/SPECS/dists

      - name: move build artifacts
        run: |
          cp -rv rpmbuild/ ~
          mv -v opencast/build/opencast-dist-*.tar.gz ~/rpmbuild/SOURCES/

      - name: build rpms
        working-directory: /github/home/rpmbuild/SPECS
        run: |
          for dist in $(cat dists); do
            rpmbuild -ba -D "ocdist ${dist}" opencast.spec
          done

      - name: list rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          ls -lh

      - name: configure s3cmd
        env:
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: |
          dnf install s3cmd
          cp s3cfg ~/.s3cfg
          sed -i "s/S3_KEY/${S3_KEY}/" ~/.s3cfg
          sed -i "s/S3_SECRET/${S3_SECRET}/" ~/.s3cfg

      - name: publish rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          ocversion=$(sed -n 's/%define srcversion \(.*\)$/\1/p' ../..//SPECS/opencast.spec)
          for file in *.rpm; do
            s3cmd put --no-check-md5 "${file}" "s3://public/$(ocversion)/${file}"
          done
