name: Build RPMs

on:
  workflow_dispatch:
  push:
    branches:
      - 'r/*'

env:
  OC_VERSION: 14

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - "8"
          - "9"
    name: build (el${{ matrix.osversion }})
    runs-on: ubuntu-latest
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:el${{ matrix.osversion }}-oc14
    steps:
      - uses: actions/checkout@v3

      - name: cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: clone mvn.opencast.org
        run: |
          git clone --depth 1 https://github.com/opencast/mvn.opencast.org.git

      - name: clone opencast
        run: |
          git clone --branch r/${OC_VERSION}.x --depth 1 https://github.com/opencast/opencast.git

      - name: prepare additional maven repository
        working-directory: opencast
        run: |
          sed -i "s#https://mvn.opencast.org/#file://$(readlink -f ../mvn.opencast.org)#" pom.xml

      - name: build opencast
        working-directory: opencast
        run: >
          mvn
          --batch-mode
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dcheckstyle.skip=true
          -DskipTests
          clean install

      - name: list distributions to build
        run: |
          find opencast/build/ -type f -name 'opencast-dist-*gz' \
            | sed 's/^.*opencast-dist-\([^-]*\)-.*$/\1/' \
            | tee rpmbuild/SPECS/dists

      - name: move build artifacts
        run: |
          cp -rv rpmbuild/ ~
          mv -v opencast/build/opencast-dist-*.tar.gz ~/rpmbuild/SOURCES/

      - name: define rpm version
        run: |
          echo "%octarversion ${OC_VERSION}-SNAPSHOT" >> ~/.rpmmacros
          echo "%ocversion ${OC_VERSION}" >> ~/.rpmmacros
          echo "%ocrelease 0.$(date +%Y%m%d%H%M%S)" >> ~/.rpmmacros

      - name: build repository rpm
        working-directory: /github/home/rpmbuild/SPECS
        run: |
          rpmbuild -ba opencast-repository.spec

      - name: build rpms
        working-directory: /github/home/rpmbuild/SPECS
        run: |
          for dist in $(cat dists); do
            rpmbuild -ba -D "ocdist ${dist}" opencast.spec
          done

      - name: list rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          du -hs opencast*.rpm

      - name: prepare gpg
        env:
          GPG_KEY: ${{ secrets.GPG_KEY_OC14 }}
        run: |
          echo "${GPG_KEY}" | gpg --import
          echo '%_gpg_name cloud@opencast.org' >> ~/.rpmmacros

      - name: sign rpms
        working-directory: /github/home/rpmbuild/RPMS/noarch
        run: |
          rpmsign --addsign *.rpm

      - name: configure s3cmd
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          echo "host_base = ${S3_HOST}" > "$HOME/.s3cfg"
          echo "host_bucket = ${S3_HOST}" >> "$HOME/.s3cfg"
          echo "bucket_location = us-east-1" >> "$HOME/.s3cfg"
          echo "use_https = True" >> "$HOME/.s3cfg"
          echo "access_key = ${S3_ACCESS_KEY}" >> "$HOME/.s3cfg"
          echo "secret_key = ${S3_SECRET_KEY}" >> "$HOME/.s3cfg"
          echo "signature_v2 = False" >> "$HOME/.s3cfg"

      - name: install createrepo-s3
        run: |
          install -m 0755 -p -D .github/createrepo-s3 /usr/bin/createrepo-s3

      - name: publish repository rpm
        working-directory: /github/home/rpmbuild/RPMS/
        run: |
          createrepo-s3 noarch/ "s3://opencast-pkg/rpms/testing/el/${{ matrix.osversion }}/oc-14/noarch"
