name: Update Repository Metadata

on:
  workflow_call:
    inputs:
      oc-version:
        required: true
        type: string
      os-version:
        required: true
        type: string
      arch:
        required: true
        type: string
      repo:
        required: true
        type: string

concurrency:
  group: ${{ inputs.repo }}/${{ inputs.os-version }}/${{ inputs.oc-version }}/${{ inputs.arch }}
  cancel-in-progress: false

jobs:
  createrepo:
    name: createrepo (el${{ matrix.osversion }}, ${{ matrix.repo }}/${{ matrix.arch }})
    runs-on: ubuntu-latest
    env:
      s3path: repository/rpms/${{ inputs.repo }}/el/${{ inputs.os-version }}/oc-${{ inputs.oc-version }}/${{ inputs.arch }}
    steps:

      - name: install dependencies
        run: >
          sudo apt install s3fs createrepo-c

      - name: create repository directory
        run: |
          mkdir repository

      - name: configure s3fs
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          echo "${S3_ACCESS_KEY}:${S3_SECRET_KEY}" > .s3fs
          chmod 600 .s3fs

      - name: mount s3fs
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
        run: >
          s3fs opencast-pkg repository
          -o passwd_file=.s3fs
          -o use_path_request_style
          -o url=https://${S3_HOST}
          -o default_acl=public-read

      - name: create repository folder
        run: |
          mkdir -p "${s3path}"

      - name: update repository metadata
        working-directory: ${{ env.s3path }}
        run: |
          set -eu
          if [ -d repodata ]; then
            createrepo_c --update .
          else
            createrepo_c .
          fi
