name: Update Repository Metadata

on:
  workflow_dispatch:
  push:
    branches:
      - 'r/*'
    paths:
      - .github/workflows/createrepo.yml

concurrency:
  group: opencast-rpmbuild
  cancel-in-progress: false

env:
  OC_VERSION: 14

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - 8
          - 9
    name: createrepo (el${{ matrix.osversion }})
    runs-on: ubuntu-latest
    steps:

      - name: install dependencies
        run: >
          apt install s3fs createrepo

      - name: create repository directory
        run: |
          mkdir repository

      - name: configure s3fs
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          echo "${S3_ACCESS_KEY}:${S3_SECRET_KEY}" > .s3fs
          chmod 600 .s3fs

      - name: mount s3fs
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
        run: >
          s3fs opencast-pkg repository
          -o passwd_file=~/.s3fs
          -o use_path_request_style
          -o url=https://${S3_HOST}

      - name: publish repository rpm
        run: |
          ls -lh repository
