name: Initialize Repositories

on:
  push:
    branches:
      - 'r/*'

concurrency:
  group: opencast-rpmbuild
  cancel-in-progress: false

env:
  OC_VERSION: 14

jobs:
  build:
    strategy:
      matrix:
        osversion:
          - 7
          - 8
          - 9
    name: build (el${{ matrix.osversion }})
    runs-on: ubuntu-latest
    container:
      image: docker.io/lkiesow/opencast-rpmbuild:el${{ matrix.osversion }}-oc14
    steps:
      - uses: actions/checkout@v3

      - name: configure s3cmd
        env:
          S3_HOST: ${{ secrets.S3_HOST }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          echo "host_base = ${S3_HOST}" > "$HOME/.s3cfg"
          echo "host_bucket = ${S3_HOST}" >> "$HOME/.s3cfg"
          echo "bucket_location = us-east-1" >> "$HOME/.s3cfg"
          echo "use_https = True" >> "$HOME/.s3cfg"
          echo "access_key = ${S3_ACCESS_KEY}" >> "$HOME/.s3cfg"
          echo "secret_key = ${S3_SECRET_KEY}" >> "$HOME/.s3cfg"
          echo "signature_v2 = False" >> "$HOME/.s3cfg"

      - name: install ensurerepo-s3
        run: |
          install -m 0755 -p -D .github/ensurerepo-s3 /usr/bin/ensurerepo-s3

      - name: initialize testing (x86_64)
        run: |
          ensurerepo-s3 "s3://opencast-pkg/rpms/testing/el/${{ matrix.osversion }}/oc-${OC_VERSION}/x86_64"

      - name: initialize release (x86_64)
        run: |
          ensurerepo-s3 "s3://opencast-pkg/rpms/release/el/${{ matrix.osversion }}/oc-${OC_VERSION}/x86_64"

      - name: initialize release (noarch)
        run: |
          ensurerepo-s3 "s3://opencast-pkg/rpms/release/el/${{ matrix.osversion }}/oc-${OC_VERSION}/x86_64"
